
***NOTE: Messages are organized per MPI process in separate sections below.


**********************************
*  Message file output, cpu #1   *
**********************************


**********************************
*  Message file output, cpu #2   *
**********************************


**********************************
*  Message file output, cpu #3   *
**********************************


**********************************
*  Message file output, cpu #4   *
**********************************

